Repository php-curl-class/php-curl-class, pull requests merged in 2023-06, with the labels that each got.

#789 Add test server support for specifying which requests fail and succeed
  tests/server.php
Labels: cleanup-no-release-required

#790 Make method to display curl option value public
  README.md
  examples/curl_display_curl_option_value.php
  examples/curl_display_curl_option_values.php
  examples/curl_display_curl_option_values_user_set.php
  src/Curl/Curl.php
  tests/PHPCurlClass/PHPMultiCurlClassTest.php
Labels: minor-backwards-compatible-added-functionality

#792 Replace `uniqid` by `random_bytes`
  src/Curl/Curl.php
Labels: Accepted
