Repository php-curl-class/php-curl-class, pull requests merged in 2024-08, with the labels that each got.

#877 Update pre-commit dependencies
  .pre-commit-config.yaml
Labels: cleanup-no-release-required, dependencies, github_actions

#882 Use nullable type declaration
  src/Curl/CaseInsensitiveArray.php
Labels: patch-backwards-compatible-bug-fixes

#887 Drop support for PHP 7.1
  .github/workflows/ci.yml
  README.md
  composer.json
  tests/check_coding_standards.sh
  tests/dockerfiles/php71/1_build.sh
  tests/dockerfiles/php71/2_start.sh
  tests/dockerfiles/php71/3_test.sh
  tests/dockerfiles/php71/4_stop.sh
  tests/dockerfiles/php71/Dockerfile
  tests/dockerfiles/php71/attach.sh
  tests/dockerfiles/php71/run.sh
  tests/dockerfiles/php71/run_interactive.sh
Labels: major-incompatible-changes

#888 Drop support for PHP 7.2
  .github/workflows/ci.yml
  README.md
  composer.json
  tests/check_coding_standards.sh
  tests/dockerfiles/php72/1_build.sh
  tests/dockerfiles/php72/2_start.sh
  tests/dockerfiles/php72/3_test.sh
  tests/dockerfiles/php72/4_stop.sh
  tests/dockerfiles/php72/Dockerfile
  tests/dockerfiles/php72/attach.sh
  tests/dockerfiles/php72/run.sh
  tests/dockerfiles/php72/run_interactive.sh
Labels: major-incompatible-changes

#889 Drop support for PHP 7.3
  .github/workflows/ci.yml
  README.md
  composer.json
  tests/check_coding_standards.sh
  tests/dockerfiles/php73/1_build.sh
  tests/dockerfiles/php73/2_start.sh
  tests/dockerfiles/php73/3_test.sh
  tests/dockerfiles/php73/4_stop.sh
  tests/dockerfiles/php73/Dockerfile
  tests/dockerfiles/php73/attach.sh
  tests/dockerfiles/php73/run.sh
  tests/dockerfiles/php73/run_interactive.sh
Labels: major-incompatible-changes
