Repository php-curl-class/php-curl-class, pull requests merged in 2025-02, with the labels that each got.

#920 Update pre-commit dependencies
  tests/.pre-commit-config.yaml
Labels: cleanup-no-release-required, dependencies, github_actions

#923 Use default for Psalm ensureOverrideAttribute
  src/Curl/CaseInsensitiveArray.php
  src/Curl/Curl.php
  src/Curl/MultiCurl.php
  tests/psalm.xml
Labels: patch-backwards-compatible-bug-fixes

#926 Actually increase psalm strictness
  tests/psalm.xml
  tests/psalm_7.4.xml
Labels: cleanup-no-release-required

#928 ⬆ Update pre-commit dependencies
  tests/.pre-commit-config.yaml
Labels: cleanup-no-release-required, dependencies, github_actions
