Repository php-curl-class/php-curl-class, pull requests merged in 2025-01, with the labels that each got.

#904 Minor clean up
  tests/ci.sh
  tests/run.sh
Labels: cleanup-no-release-required

#906 Add flair to version bump pull requests
  .github/dependabot.yml
Labels: cleanup-no-release-required

#908 Increase PHPStan strictness
  phpstan.neon
  scripts/bump_major_version.php
  scripts/bump_minor_version.php
  scripts/bump_patch_version.php
  src/Curl/CaseInsensitiveArray.php
  src/Curl/Decoder.php
  src/Curl/MultiCurl.php
  tests/run_static_analysis_check_phpstan.sh
Labels: patch-backwards-compatible-bug-fixes

#916 Update pre-commit dependencies
  tests/.pre-commit-config.yaml
Labels: cleanup-no-release-required, dependencies, github_actions
